// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity_framework.entity;

#nullable disable

namespace entity_framework.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20250317232725_update data seeding")]
    partial class updatedataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entity_framework.Models.Department", b =>
                {
                    b.Property<int?>("depId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("depId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("alex")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("deptNAme");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("int ");

                    b.Property<int?>("manger_id")
                        .HasColumnType("int");

                    b.HasKey("depId");

                    b.HasIndex("manger_id")
                        .IsUnique()
                        .HasFilter("[manger_id] IS NOT NULL");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("entity_framework.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasDefaultValue("monsoure")
                        .HasColumnName("Employeeadress");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dep_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dep_id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("entity_framework.Models.Student_Course", b =>
                {
                    b.Property<int>("Stu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Cour_Id")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("Stu_Id", "Cour_Id");

                    b.HasIndex("Cour_Id");

                    b.ToTable("Student_Course");
                });

            modelBuilder.Entity("entity_framework.Models.course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("course");
                });

            modelBuilder.Entity("entity_framework.Models.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("entity_framework.Models.Department", b =>
                {
                    b.HasOne("entity_framework.Models.Employee", "manger")
                        .WithOne("manger_department")
                        .HasForeignKey("entity_framework.Models.Department", "manger_id");

                    b.Navigation("manger");
                });

            modelBuilder.Entity("entity_framework.Models.Employee", b =>
                {
                    b.HasOne("entity_framework.Models.Department", "EMployeeDepatment")
                        .WithMany("employees")
                        .HasForeignKey("dep_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("entity_framework.Models.Address", "empaddress", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("id")
                                .HasColumnType("int");

                            b1.Property<string>("street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("EMployeeDepatment");

                    b.Navigation("empaddress")
                        .IsRequired();
                });

            modelBuilder.Entity("entity_framework.Models.Student_Course", b =>
                {
                    b.HasOne("entity_framework.Models.course", "courses")
                        .WithMany("Course_Student")
                        .HasForeignKey("Cour_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("entity_framework.Models.student", "students")
                        .WithMany("student_Courses")
                        .HasForeignKey("Stu_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("students");
                });

            modelBuilder.Entity("entity_framework.Models.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("entity_framework.Models.Employee", b =>
                {
                    b.Navigation("manger_department");
                });

            modelBuilder.Entity("entity_framework.Models.course", b =>
                {
                    b.Navigation("Course_Student");
                });

            modelBuilder.Entity("entity_framework.Models.student", b =>
                {
                    b.Navigation("student_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
